defaults:
  - hydra/launcher: rq

n_epochs: 1
batch_size: 1
debug: False
n_cores: 1
n_workers: 1
n_layer: 2
n_embd: 64
n_head: 2
lr: 1e-4
val_step: 100
# "--add_positions
log_console: True
# "--padding
# "--maxn: 614
maxn: 1024
