# @package _global_

add_positions: false
padding: false
tasks: ["datasets/data/training/0a938d79.json"]
end_line_token: 10
promt_token: 11
end_episode_token: 12
pad_token: 13
split: (0.9,0.1) # only train and val
transforms:
  [
    [
      {
        _target_: datasets.transforms.ColorPermutation,
        max_colors: 10,
        limit: 1000,
      },
    ],
    [
      {
        _target_: datasets.transforms.ColorPermutation,
        max_colors: 10,
        limit: 1000,
      },
    ],
    [
      {
        _target_: datasets.transforms.ColorPermutation,
        max_colors: 10,
        limit: 1000,
      },
    ],
  ]
